language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get -u -v github.com/lestrrat/go-file-rotatelogs
  - go get -u -v github.com/pkg/errors
  - go get -u -v github.com/rifflock/lfshook
  - go get -u -v github.com/sirupsen/logrus
script:
  - go test -race -v ./...
