version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: go get -u -v github.com/lestrrat/go-file-rotatelogs
      - run: go get -u -v github.com/pkg/errors
      - run: go get -u -v github.com/rifflock/lfshook
      - run: go get -u -v github.com/sirupsen/logrus
      - run: go test -trace -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
